name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build macOS App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Release Configuration
        run: |
          xcodebuild -project SuperWhisper/SuperWhisper/SuperWhisper.xcodeproj \
            -scheme SuperWhisper -configuration Release \
            -derivedDataPath build
      - name: Archive .app
        run: |
          mkdir -p artifact
          ditto -c -k --sequesterRsrc --keepParent \
            build/Build/Products/Release/SuperWhisper.app artifact/SuperWhisper-macOS.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SuperWhisper-macOS
          path: artifact/SuperWhisper-macOS.zip